Full MSVC support and bug fixes.
alibaba/yalantinglibs pull request #35
Opened 2022-11-01 20:47 UTC by refvalue

## Why

Closes #18 
Made this repo available to MSVC.

## What is changing

Added:
- util/magic_names.hpp
- util/meta_string.hpp
- A uniform MSVC/GCC/Clang implementation of reflecting qualified function name.
- A meta_string class for template programming as non-type parameter when enabling C++20.

Added:
- util/benchmark
- util/examples
- util/tests Some static asserts for ensuring correctness of newly added code.

Modified/Fixed:
- coro_rpc: CMakeLists.txt
- coro_rpc/remote.hpp
- util/function_name.h Fixed fatal issues when compiling with MSVC.
Replaced -pthread with the Threads::Threads CMake package to eliminate MSVC warnings.
Fixed incorrect function names when using MSVC.

All unit tests have passed on MSVC 19.3x/GCC11.x/12.x/Clang 15+.
Core logics have passed on GoldBolt.

## Example
Please view src/util/tests

2022-11-01 20:55 UTC, poor-circle commented
Thank you very much!

2022-11-01 20:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/yalantinglibs?pullRequest=35) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/yalantinglibs?pullRequest=35) before we can accept your contribution.<br/><hr/>**refvalue** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/yalantinglibs?pullRequest=35) it.</sub>

2022-11-02 01:10 UTC, PikachuHyA commented
good job

2022-11-02 01:36 UTC, qicosmos commented
Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/yalantinglibs?pullRequest=35) before we can accept your contribution.
@refvalue

2022-11-02 01:51 UTC, PikachuHyA commented
The CI is added by https://github.com/alibaba/yalantinglibs/pull/33. However, only `struct_pack` enabled on MSVC.
Please change the `yaLanTingLibs_ENABLE_PROJECTS=all` to enable all projects on MSVC and verify your code.
https://github.com/alibaba/yalantinglibs/blob/657718f346c66e1c4dcb1165531b2e4c6c3b75af/.github/workflows/windows.yml#L42
note: Windows Server 2022 is used in CI.

2022-11-02 01:57 UTC, PikachuHyA requested changes
Thanks for your work. 
Please rebase to the latest main branch, and pass the CI.

2022-11-02 01:57 UTC, PikachuHyA commented on src/util/CMakeLists.txt
> +message("The \"util\" project does not need a main project.")
please use `message(STATUS message_string)`
```
message(STATUS "The \"util\" project does not need a main project.")
```

2022-11-02 01:57 UTC, PikachuHyA commented on src/util/benchmark/CMakeLists.txt
> +message("The \"util\" project does not need a benchmark.")
please use `message(STATUS message_string)`

2022-11-02 01:57 UTC, PikachuHyA commented on src/util/examples/CMakeLists.txt
> +message("The \"util\" project does not contain examples. Please read the \"tests\" for your information.")
please use `message(STATUS message_string)`

2022-11-02 01:57 UTC, PikachuHyA commented on src/coro_rpc/benchmark/client/CMakeLists.txt
> +target_link_libraries(benchmark_data_gen PRIVATE libcoro_rpc Threads::Threads)
I have fixed the `-pthread` problem by https://github.com/alibaba/yalantinglibs/pull/30 yesterday.
please rebase to the latest main branch.

2022-11-02 01:57 UTC, PikachuHyA commented on src/util/tests/static_asserts.cpp
> +int main() {}
add a newline is better 😊

2022-11-02 02:47 UTC, closed without merging

2022-11-02 02:51 UTC, refvalue commented
> Thanks for your work. Please rebase to the latest main branch, and pass the CI.

OK. I will create a new PR later.

2022-11-02 04:44 UTC, refvalue commented
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/yalantinglibs?pullRequest=35) before we can accept your contribution. @refvalue

Thanks! I has forked a new repo with a new PR, for the previous fork had an incorrect email. Now everything goes well.

2022-11-02 04:46 UTC, refvalue commented
> Thank you very much!

Thank you!